[package]
name = "fractal_explorer"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.25.2", features = ["derive"] }
console_error_panic_hook = "0.1.7"
futures-channel = "0.3.34"
log = "0.4.34"
wasm-bindgen = "0.2.129"
wasm-bindgen-futures = "0.4.79"
web-sys = { version = "0.3.106", features = ["HtmlCanvasElement", "console"] }
wgpu = "30"

[lib]
crate-type = ["cdylib", "rlib"]

[dev-dependencies]
naga = { version = "30", features = ["wgsl-in"] }

[profile.release]
opt-level = "s"
lto = true
